name: Upload Godot artifact
description: 上传 Godot 构建产物。

inputs:
  name:
    description: 产物名称。
    default: ${{ github.job }}
  path:
    description: 要上传的路径。
    required: true
    default: bin/*
  retention-days:
    description: 产物保留天数（GitHub 默认 90）。
    default: 60

runs:
  using: composite
  steps:
    - name: 上传 Godot 构建产物
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: ${{ inputs.retention-days }}
